/**
 * Shared utilities for credit card date math.
 *
 * The data model: `accounts.closing_date` and `accounts.due_date` are manual,
 * persistent anchor dates. They do NOT auto-advance. The full sequence of
 * statement closings (or due dates) for a card is generated by adding/subtracting
 * whole months from the anchor. End-of-month dates are clamped to the last
 * valid day of the target month — e.g. anchor 2026-01-31 + 1 month = 2026-02-28.
 *
 * Deno-compatible: uses only the built-in `Date` API.
 */

/**
 * Parses an ISO date string (YYYY-MM-DD) into a UTC-midday Date.
 * Using midday avoids DST/timezone shifts that can flip the calendar day.
 */
export function parseISODate(dateStr: string): Date {
  // Accept "YYYY-MM-DD" or full ISO strings.
  const trimmed = dateStr.length === 10 ? dateStr + "T12:00:00Z" : dateStr;
  return new Date(trimmed);
}

/**
 * Formats a Date as ISO date (YYYY-MM-DD), using its UTC components so the
 * day doesn't drift across timezones.
 */
export function formatISODate(date: Date): string {
  const y = date.getUTCFullYear();
  const m = String(date.getUTCMonth() + 1).padStart(2, "0");
  const d = String(date.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

/**
 * Adds `n` whole months to `date`, clamping the day to the last valid day of
 * the target month. Mirrors date-fns `addMonths`. Negative `n` works too.
 *
 * Example: addMonthsClamped(2026-01-31, 1) -> 2026-02-28
 *          addMonthsClamped(2026-03-31, -1) -> 2026-02-28
 */
export function addMonthsClamped(date: Date, n: number): Date {
  const year = date.getUTCFullYear();
  const month = date.getUTCMonth();
  const day = date.getUTCDate();

  const targetMonthIndex = month + n;
  // last day of the target month (use day 0 of month+1)
  const lastDayOfTargetMonth = new Date(
    Date.UTC(year, targetMonthIndex + 1, 0)
  ).getUTCDate();

  const clampedDay = Math.min(day, lastDayOfTargetMonth);
  return new Date(Date.UTC(year, targetMonthIndex, clampedDay, 12, 0, 0));
}

/**
 * Adds `n` months to an ISO date string (YYYY-MM-DD), returning ISO format.
 */
export function addMonthsClampedISO(dateStr: string, n: number): string {
  return formatISODate(addMonthsClamped(parseISODate(dateStr), n));
}

/**
 * Returns the difference in whole calendar months between two dates,
 * rounded by day-of-month (mirroring date-fns `differenceInCalendarMonths` is
 * not what we want here — we want to know how many `addMonthsClamped` steps
 * to go from `from` to a date >= `target`).
 *
 * Internal helper for the walk-forward loop.
 */
function approxMonthDiff(from: Date, to: Date): number {
  return (
    (to.getUTCFullYear() - from.getUTCFullYear()) * 12 +
    (to.getUTCMonth() - from.getUTCMonth())
  );
}

/**
 * Compares two dates by calendar day only (ignoring time of day).
 * Returns negative if a < b, 0 if same day, positive if a > b.
 */
function compareDays(a: Date, b: Date): number {
  const da = Date.UTC(a.getUTCFullYear(), a.getUTCMonth(), a.getUTCDate());
  const db = Date.UTC(b.getUTCFullYear(), b.getUTCMonth(), b.getUTCDate());
  return da - db;
}

/**
 * Given an anchor date and a reference date, returns the first occurrence
 * (anchor + N months, clamped) such that the result is >= reference.
 *
 * Used to find the closing date for a given expense, or to roll a due_date
 * anchor forward to the next upcoming due date relative to today.
 *
 * Returns ISO date string (YYYY-MM-DD).
 */
export function nextOccurrenceOnOrAfter(
  anchorISO: string,
  referenceISO: string
): string {
  const anchor = parseISODate(anchorISO);
  const reference = parseISODate(referenceISO);

  // Start with a heuristic guess to avoid an O(years) loop in pathological cases.
  let n = approxMonthDiff(anchor, reference);
  let candidate = addMonthsClamped(anchor, n);

  // Walk forward until candidate >= reference.
  // Bounded by a small constant in normal cases (<=2 iters).
  while (compareDays(candidate, reference) < 0) {
    n += 1;
    candidate = addMonthsClamped(anchor, n);
  }

  // If we overshot during the heuristic, walk back.
  while (n > 0) {
    const prev = addMonthsClamped(anchor, n - 1);
    if (compareDays(prev, reference) >= 0) {
      n -= 1;
      candidate = prev;
    } else {
      break;
    }
  }

  return formatISODate(candidate);
}

/**
 * Returns the closing date (ISO) for the statement that contains an expense
 * dated `expenseISO`, given the card's `closingAnchorISO`.
 *
 * For an expense E, its statement is the first closing >= E.
 *
 * Returns null if `closingAnchorISO` is null/undefined.
 */
export function getStatementClosingForExpense(
  closingAnchorISO: string | null | undefined,
  expenseISO: string
): string | null {
  if (!closingAnchorISO) return null;
  return nextOccurrenceOnOrAfter(closingAnchorISO, expenseISO);
}

/**
 * Returns the next due date (ISO) at or after `referenceISO` from the
 * `dueAnchorISO` series. Returns null if anchor is null/undefined.
 */
export function getNextDueDate(
  dueAnchorISO: string | null | undefined,
  referenceISO: string
): string | null {
  if (!dueAnchorISO) return null;
  return nextOccurrenceOnOrAfter(dueAnchorISO, referenceISO);
}

/**
 * Returns the difference in whole days between two ISO dates (b - a).
 * Treats both dates as calendar days (ignores time-of-day).
 */
export function daysBetweenISO(aISO: string, bISO: string): number {
  const a = parseISODate(aISO);
  const b = parseISODate(bISO);
  const da = Date.UTC(a.getUTCFullYear(), a.getUTCMonth(), a.getUTCDate());
  const db = Date.UTC(b.getUTCFullYear(), b.getUTCMonth(), b.getUTCDate());
  return Math.round((db - da) / (1000 * 60 * 60 * 24));
}

/**
 * Returns the start of the statement period (i.e., the day AFTER the previous
 * closing) for the statement that closes on `closingISO`, given the anchor.
 */
export function getStatementStart(
  closingAnchorISO: string,
  statementClosingISO: string
): string {
  // Previous closing in the series:
  const anchor = parseISODate(closingAnchorISO);
  const closing = parseISODate(statementClosingISO);
  const n = approxMonthDiff(anchor, closing);
  // closing should equal addMonthsClamped(anchor, n); guard against off-by-one.
  let nFinal = n;
  if (
    formatISODate(addMonthsClamped(anchor, n)) !==
    formatISODate(closing)
  ) {
    // Try n+1 / n-1 to recover.
    if (
      formatISODate(addMonthsClamped(anchor, n + 1)) ===
      formatISODate(closing)
    ) {
      nFinal = n + 1;
    } else if (
      formatISODate(addMonthsClamped(anchor, n - 1)) ===
      formatISODate(closing)
    ) {
      nFinal = n - 1;
    }
  }
  const prevClosing = addMonthsClamped(anchor, nFinal - 1);
  // Period start is the day after the previous closing.
  const start = new Date(
    Date.UTC(
      prevClosing.getUTCFullYear(),
      prevClosing.getUTCMonth(),
      prevClosing.getUTCDate() + 1,
      12,
      0,
      0
    )
  );
  return formatISODate(start);
}
